# limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;

server {
    listen 80;

    # Xử lý preflight requests (OPTIONS)
    location / {
        # limit_req zone=one burst=10 nodelay; # Giới hạn 5 yêu cầu mỗi IP, không cho phép chậm trễ        
        # limit_req_status 429;
        
        proxy_pass http://server:3000;
     
        # --- Cấu hình Header cơ bản ---
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # --- Cấu hình quan trọng cho WebSocket (Socket.io) ---
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # --- Cấu hình cho WebRTC & Streaming (Tránh bị ngắt kết nối giữa chừng) ---
        proxy_read_timeout 86400s; # Giữ kết nối mở trong 24h nếu không có dữ liệu
        proxy_send_timeout 86400s;
        proxy_connect_timeout 75s;

        # --- Vô hiệu hóa Buffering (Rất quan trọng cho Real-time) ---
        proxy_buffering off;
        proxy_cache_bypass $http_upgrade;
    }
}